cache:
  directories:
    - "node_modules"
    - "docs"
    - "examples"

language: node_js

before_script:
  - npm install

env:
   - NODE_ENV=production

node_js:
  - "8"
script:
  - npm run lint
  - npm run test