cache:
  directories:
    - "node_modules"
    - "docs"
    - "examples"

language: node_js

before_script:
  - yarn install

env:
   - NODE_ENV=production

node_js:
  - "8"
script:
  - yarn run lint
  - yarn run test